version: '3'
services:
  api:
    image: mohinesh27/nodeauth
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - backend
    ports:
      - "27017:27017"

  web-cli:
    image: mohinesh27/nodeauth
    links:
      - mongo
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge